name: new-project
description: Create the folders and readme for a new project
inputs:
  - label: Nome do projeto
    type: text
    name: name_projeto
    default: new_project
    required: 'true'
  - label: Estado do projeto
    type: text
    name: state_project
    required: 'true'
    items:
      - Desenvolvimento
      - Usar
      - Depreciado
  - label: Fase
    type: text
    name: phase_project
    required: 'true'
    items:
      - Experimentos
      - Desenvolvimento
      - QA
      - Homologação
      - Produção
  - label: Linguagens
    type: text
    name: languages_project
    required: 'true'
  - label: Descrição
    type: text
    name: description_project
    required: 'true'
  - label: Usar padrao?
    type: bool
    name: default
supported-os:
- mac
command: sh tasks/add.sh {{default}} {{name_projeto}} {{state_project}} {{phase_project}} "{{description_project}}" "{{languages_project}}"
  # - linux:  ./add.sh
  # - mac: sh ./add.sh
  # - windows: cmd /c ./add.sh
